### ISSUE TITLE
Add examples for Site Content regions (Header/Footer)

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core.docs#10]
hi   thanks for your great work 
i need to add header and footer Regions should only i add it to template (as i see in documents ) or should add code to manager 
what the step by step way to made this goal 
regards

**Comment by r4g-jon** [comment]
Thanks @tidyui!

I will try to get something typed up over the next week or so (I need to set Statica up first) and will some of the notes I've made which should hopefully help others.

**Comment by tidyui** [comment]
Closing as this has been contributed by @r4g-jon
