### ISSUE TITLE
Best way to handle secret page

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core.docs#18]
I would like to implement a secret page.
- User goes to a page /secret/page, but it has an authorize decorator, which takes you to the login page. Once you login, you get to see what is on this page.

The little I have gathered, is to add this to the startup.cs
```csharp
App.Permissions["Application"].Add(new Piranha.Security.PermissionItem
{
    Name = "WebUser",
    Title = "Web User"
});
```
Then in my controller, I add this

```csharp
        [Authorize(Roles="Buyer")]
        [Route("page")]
        public async Task<IActionResult> TraustiPage(Guid id, bool draft = false)
```
I have set a role Buyer to include WebUser. Other than that, he does not have any other rights.
I am correctly taken to the login page, with the correct redirect url, like 
```url
http://localhost:5000/manager/login?ReturnUrl=%2Ftrausti%2Fpage
```

But once I do login, I go back to the /manager site with the following url
```
http://localhost:5000/manager/login?ReturnUrl=%2FManager
```
I am using Piranha CMS template for Web, version 8.1.0

**Comment by tidyui** [comment]
This ties into the following issue https://github.com/PiranhaCMS/piranha.core/issues/1076
