### ISSUE TITLE
Media Versions

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core.docs#36]
I noticed that Media and has the Media versions. All the images I have uploaded to the system do have thumbnails.
How do I access them? The Media.Versions.Object does not seem to have any way of generating url for the thumbnail?
Short question, how can I get the thumbnail if available?

**Comment by tidyui** [comment]
Hi there! Take a look a this article:

https://piranhacms.org/docs/architecture/image-processing

Best regards
