### ISSUE TITLE
Where can I set up Chinese?

### ISSUE THREAD

**Issue by SAssassin** [PiranhaCMS/piranha.core.docs#57]
![image](https://user-images.githubusercontent.com/26713143/97110439-3f141e80-1714-11eb-81e5-c581ec3a45bd.png)  
According to the official website, after five minutes of construction, some of them will be in Chinese, but not all of them will be displayed, and no items will be set.

**Comment by tidyui** [comment]
You can contribute to the translations here: https://crowdin.com/project/piranhacms Chinese is only 89% complete atm
