### ISSUE TITLE
Techniques For Securing Pages - Razor Pages

### ISSUE THREAD

**Issue by Glorfinkel** [PiranhaCMS/piranha.core.docs#9]
Hey guys, 
is there a tutorial quite similar to your blog post for securing pages, but for razorpages?
What i am trying to do is making a blog secret, so only logged in user can read it.

I think i'm failing in setting the routing, because in manager all content types are shown correctly, are editable and so on.
If i try to access the blog only generates an 404 Error.
I tried setting the route at the razorpage of the archive itself, but no success.

Maybe i missed some at the endpoints or something else?

` app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapPiranhaManager();
            });`

Thank you so much for your help!

Greetings, 
Glorfinkel

**Comment by Glorfinkel** [comment]
Oh @tidyui, thank you so much! You won't believe it. 
I missed the '~' in the @page route. :-/ Sorry for wasting your time - but a section in the docs would be nice.

**Comment by tidyui** [comment]
We have new features for this is 8.1, check out the docs section for this!
