### ISSUE TITLE
Remove references to PageTypeRouteAttribute

### ISSUE THREAD

**Issue by jasonterando** [PiranhaCMS/piranha.core.docs#96]
Hi, I found [this Piranha tutorial page](https://piranhacms.org/blog/techniques-for-securing-pages) on securing pages using Piranha CMS.  It refers to an attribute called PageTypeRoute which looks like it got added [in this commit back in 2017](https://github.com/PiranhaCMS/piranha.core/commit/1f583c608df9136f7f580b7dc844739143dfa780), but is no longer in the [master](https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha.AttributeBuilder) branch.

Did this attribute get moved or is there an alternate technique I should be using to set up per-page authorization?

Thanks!

**Comment by jasonterando** [comment]
Thanks for the prompt reply!

**Comment by tidyui** [comment]
Opening this again so we remember to update the docs 🙂

**Comment by tidyui** [comment]
This technique is obsolete, the entire page should be removed.
